// Pipeline_Build_CPP_APP

pipeline {
    agent any

    stages {
        stage('Build_Ubuntu_image_with_CMake') {
            steps {
                build 'Build_Ubuntu_image_with_CMake'
            }
        }
        stage('Build_Hello_CMake_Image') {
            steps {
                build 'Build_Hello_CMake_Image'
            }
        }
    }

}