# Build and run:
#   docker build -t fred13/ubuntu-cpp -f Dockerfile.ubuntu-cpp .

FROM ubuntu:20.04

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata

RUN apt-get update \
  && apt-get install -y build-essential git cmake
